- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes

  tasks:
    - include: tasks/packages.yml
    - include: tasks/sudouser.yml
      vars:
        sudo_user: paul
        user_shell: /bin/fish
    - include: tasks/neovim.yml
      vars:
        username: paul
    - include: tasks/npm.yml
    - include: tasks/gnome.yml
    - include: tasks/java.yml
      vars:
        username: paul
    - include: tasks/terminator.yml
      vars:
        username: paul
